alternatif_critique = [
"décroissance", "décroissances", "décroissant", "décroissante", "déconsommation", "sobriété",
"sobriétés", "sobriété énergétique", "sobriété heureuse", "modération", "consommation réduite",
"consommation modérée", "réduction de la consommation", "vie sobre", "vie simple", "vie minimaliste",
"minimalisme", "simplicité volontaire", "frugalité", "autosuffisance", "auto-suffisance énergétique",
"autonomie locale", "autonomies locales", "autogestion", "autogéré", "autogérée", "coopération", "coopérative",
"coopératives", "entraide", "solidarité", "solidarités", "collectif", "collectifs", "communauté", "communautés",
"initiative citoyenne", "mobilisation citoyenne", "participation citoyenne", "engagement citoyen",
"écocitoyenneté", "citoyenneté écologique", "activisme", "militantisme", "associatif", "association citoyenne",
"réseau citoyen", "responsabilité collective", "démocratie participative", "prise de décision participative",
"co-construction", "gouvernance partagée", "gestion collective", "gestion communautaire", "gestion locale",
"planification écologique", "planification locale", "plan local", "projet collectif", "acteur local",
"acteurs locaux", "résilience", "résilience communautaire", "résilience sociale", "résilience urbaine",
"territoire résilient", "adaptation au changement climatique", "changement systémique", "transformation sociale",
"transformation politique", "structure sociale", "justice climatique", "justice environnementale",
"justice sociale", "justice économique", "équité sociale", "équité environnementale", "inégalités écologiques",
"solidarité écologique", "coopération locale", "mobilisation écologique", "mobilisation sociale",
"bien-être collectif", "qualité de vie", "cohabitation", "vie en communauté", "éducation écologique",
"sensibilisation environnementale", "réflexion critique", "questionnement systémique", "changement collectif",
"écosystème social", "écosystèmes", "protection des écosystèmes", "préservation de la biodiversité",
"biodiversité", "reforestation", "reboisement", "agroécologie", "agroécologiques", "permaculture",
"permacultures", "agriculture biologique", "agriculture durable", "agriculture régénérative", "ferme paysanne",
"fermes paysannes", "circuits courts agricoles", "culture locale", "production locale", "circuit court",
"économie circulaire", "économie sociale et solidaire", "économie collaborative", "économie de fonctionnalité",
"économie locale", "économie circulaire verte", "économie circulaire sociale", "relocalisation",
"autosuffisance locale", "consommation responsable", "consommation éthique", "commerce équitable",
"commerce responsable", "production responsable", "produits durables", "produits éthiques",
"durabilité", "réduction des déchets", "zéro déchet", "zéro déchets", "réemploi", "réutilisation",
"réparabilité", "réparation", "produit réparable", "recyclage citoyen", "recyclage", "réduction énergétique",
"réduction des impacts", "réduction de l’empreinte écologique", "écoconception", "éco-conception",
"éco-design", "gestion durable", "gestion durable des ressources", "préservation naturelle",
"préservation environnementale", "préservation sociale", "préservation écologique", "réhabilitation écologique",
"restauration écologique", "conservation", "conservation écologique", "écologie participative",
"gestion écologique", "régulation", "régulations", "réglementation", "réglementations", "politiques publiques",
"politique publique", "gouvernance environnementale", "norme environnementale", "normes durables",
"loi environnementale", "taxe carbone", "tarification du carbone", "financement vert", "fonds vert",
"subvention écologique", "subventions vertes", "recherche publique", "services publics", "planification territoriale",
"aménagement durable", "régulation écologique", "politique verte", "politiques environnementales",
"mobilité douce", "mobilités douces", "transports en commun", "transport public", "vélo", "vélos",
"usage du vélo", "marche à pied", "marche active", "piétonisation", "transports collectifs",
"transport partagé", "covoiturage", "autopartage", "mobilité partagée", "mobilité durable",
"mobilité écologique", "transport durable", "transport écologique", "mobilité active", "réduction des déplacements",
"transition écologique", "transitions écologiques", "transition durable", "transition sociale",
"transition citoyenne", "transition alimentaire", "agriculture locale", "fermes locales", "réseau local",
"initiative locale", "plan local", "partenariat citoyen", "gestion partagée", "gestion partagée des ressources",
"coopération citoyenne", "changement social", "économie locale", "circuits courts alimentaires",
"commerce local", "acteurs locaux", "collectif local", "village résilient", "territoire durable",
"planification durable", "autosuffisance énergétique", "autosuffisance locale", "relocalisation économique",
"production artisanale", "artisanat durable", "artisanat local", "consommation locale", "écosystème durable",
"préservation du vivant", "solidarité territoriale", "responsabilité environnementale", "responsabilité sociale",
"écologie politique", "écologie sociale", "écologie populaire", "justice territoriale", "autonomie alimentaire",
"agriculture paysanne", "paysan", "paysans", "réappropriation citoyenne", "bien commun", "communs",
"gestion des communs", "usage collectif", "biens communs", "ressources durables", "planification écologique",
"territoire participatif", "concertation citoyenne", "innovation sociale", "inclusion écologique",
"égalité environnementale", "climat juste", "justice climatique globale", "réduction des inégalités",
"changement comportemental", "consommation consciente", "consommation solidaire", "sobriété numérique",
"sensibilisation citoyenne", "responsabilité collective", "démocratie locale", "gouvernance citoyenne",
"économie humaine", "écologie humaine", "changement de mode de vie", "culture écologique",
"éducation populaire", "changement collectif", "partage", "entraides", "mutualisation", "usage partagé",
"partage des ressources", "solidarité sociale", "responsabilité éthique", "engagement écologique",
"acteurs citoyens", "projet citoyen", "initiatives durables", "éco-responsabilité", "réseau solidaire",
"économie équitable", "transition juste", "territoire écologique", "régénération écologique"
]

techno_solutionniste = [
"innovation", "technologie", "numérique", "robotique", "intelligence artificielle", "IA", "deep learning",
"machine learning", "big data", "algorithme", "cloud computing", "edge computing", "data center",
"informatique", "digitalisation", "transformation numérique", "start-up", "cleantech", "greentech", "green tech",
"smart city", "villes intelligentes", "mobilité connectée", "véhicule autonome", "voiture électrique",
"transport connecté", "drone", "drones", "robot livreur", "robot agricole", "robot collaboratif",
"automatisation", "automatisée", "usine intelligente", "industrie 4.0", "industrie connectée", "usine du futur",
"impression 3D", "fabrication additive", "modélisation 3D", "jumeau numérique", "simulation numérique",
"réalité virtuelle", "réalité augmentée", "métavers", "cybersystème", "cybersécurité", "blockchain", "cloud",
"IoT", "objets connectés", "capteurs", "capteurs intelligents", "capteurs urbains", "capteurs agricoles",
"réseau intelligent", "smart grid", "réseaux intelligents", "monitoring environnemental", "système intelligent",
"systèmes intelligents", "automatisation intelligente", "robot", "robots", "prothèse intelligente",
"augmentation humaine", "transhumanisme", "cybernétique", "biotechnologie", "biotechnologies", "bioingénierie",
"bioinformatique", "nanotechnologie", "nanotechnologies", "nanoscience", "nanosciences", "génétique",
"ingénierie génétique", "OGM", "organisme modifié", "bioénergie", "biocarburant", "biocarburants",
"bioraffinerie", "aéroponie", "hydroponie", "agriculture connectée", "agriculture de précision",
"agriculture intelligente", "ferme connectée", "ferme intelligente", "innovation climatique",
"technologie climatique", "modélisation climatique", "analyse climatique", "prévision climatique",
"captage du carbone", "stockage du carbone", "CCS", "séquestration du carbone", "géoingénierie",
"climate engineering", "neutralité carbone", "bilan carbone intelligent", "empreinte carbone",
"réduction d’empreinte carbone", "énergie solaire", "panneau solaire", "panneaux solaires", "photovoltaïque",
"photovoltaïques", "énergie éolienne", "éolienne", "éoliennes", "parc éolien", "hydroélectricité", "géothermie",
"centrale géothermique", "énergie marémotrice", "fusion nucléaire", "hydrogène", "hydrogène vert",
"pile à hydrogène", "batterie", "batteries", "batterie solide", "accumulateur", "accumulateurs",
"stockage énergétique", "stockage d’énergie", "microgrille", "microgrilles", "réseau de capteurs",
"infrastructure numérique", "infrastructure intelligente", "infrastructure digitale", "technologies vertes",
"technologies environnementales", "technologie propre", "industrie propre", "production durable",
"production énergétique", "optimisation énergétique", "efficacité énergétique", "smart factory",
"smart factories", "bâtiment intelligent", "bâtiments intelligents", "éco-construction", "bâtiments durables",
"design écologique", "éco-innovation", "innovation responsable", "innovation durable", "innovation verte",
"innovation technologique", "innovation numérique", "innovation énergétique", "green innovation",
"solution numérique durable", "solution technologique", "solutions technologiques", "solution innovante",
"solutions innovantes", "innovations", "innovant", "innovante", "innovantes", "modèles innovants",
"modèle innovant", "projets innovants", "projet innovant", "modernisation écologique", "économie numérique",
"économie verte", "capitalisme vert", "technocapitalisme", "technopolitique", "technopole",
"écosystème technologique", "urbanisme technologique", "ville verte", "ville connectée", "villes connectées",
"villes intelligentes", "écocité", "écocités", "usines intelligentes", "technologies avancées",
"technologies de pointe", "haute technologie", "hautes technologies", "progrès technologique",
"progrès technique", "technoscience", "techno-optimisme", "technoprogressisme", "solutionnisme technologique",
"solutionnisme numérique", "techno-utopie", "utopie technologique", "entrepreneuriat vert", "startup",
"startups", "entreprises innovantes", "entreprise innovante", "investissement durable", "finance verte",
"digital", "digitales", "digitaux", "stratégie numérique", "transition technologique", "transition énergétique",
"transition numérique", "modernisation technologique", "société connectée", "production optimisée",
"optimisation industrielle", "gestion automatisée", "gestion connectée", "gestion algorithmique",
"automatisation des processus", "détection automatisée", "maintenance prédictive", "intelligence énergétique",
"intelligence des données", "analyse de données", "analyse big data", "science des données", "data science",
"apprentissage automatique", "deep tech", "clean tech", "clean technology", "technologies climatiques",
"technologies propres", "technologie environnementale", "technologie avancée", "technologies intelligentes",
"technologie urbaine", "technologie de pointe", "ingénierie climatique", "optimisation climatique",
"monitoring", "simulation", "jumeaux numériques", "usines durables", "robot agriculteur",
"robot de livraison", "transport automatisé", "mobilité propre", "mobilité durable", "mobilité urbaine",
"mobilité intelligente", "mobilité électrique", "mobilité partagée", "transport durable", "transports intelligents",
"véhicule électrique", "véhicules électriques", "véhicules autonomes", "voitures électriques",
"voitures autonomes", "AI", "énergies renouvelables", "énergies propres", "énergies vertes",
"production d’énergie", "croissance verte", "croissance durable", "développement durable",
"sustainable growth", "innovation sociale par la technologie"
]
